In [11]:
# 📌 Step 1: Import Libraries
import pandas as pd
import numpy as np

In [13]:
# Load dataset
file_path = "Mobiles Dataset (2025).csv"
df = pd.read_csv(file_path, encoding="ISO-8859-1")

In [15]:
# Preview
df.head()

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
0,Apple,iPhone 16 128GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,"PKR 224,999","INR 79,999","CNY 5,799",USD 799,"AED 2,799",2024
1,Apple,iPhone 16 256GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,"PKR 234,999","INR 84,999","CNY 6,099",USD 849,"AED 2,999",2024
2,Apple,iPhone 16 512GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,"PKR 244,999","INR 89,999","CNY 6,499",USD 899,"AED 3,199",2024
3,Apple,iPhone 16 Plus 128GB,203g,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,"PKR 249,999","INR 89,999","CNY 6,199",USD 899,"AED 3,199",2024
4,Apple,iPhone 16 Plus 256GB,203g,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,"PKR 259,999","INR 94,999","CNY 6,499",USD 949,"AED 3,399",2024

In [24]:
import re

def extract_number(text):
    """
    Extracts number(s) from a string.
    If multiple numbers, return the maximum.
    """
    if pd.isna(text):
        return np.nan
    numbers = re.findall(r"\d+\.?\d*", str(text))  # find numbers
    if not numbers:
        return np.nan
    numbers = [float(n) for n in numbers]
    return max(numbers)   # take max (e.g., "8 / 12" -> 12)

# Apply function to columns
df["RAM"] = df["RAM"].apply(extract_number)
df["Front Camera"] = df["Front Camera"].apply(extract_number)
df["Back Camera"] = df["Back Camera"].apply(extract_number)
df["Mobile Weight"] = df["Mobile Weight"].apply(extract_number)
df["Battery Capacity"] = df["Battery Capacity"].apply(extract_number)
df["Screen Size"] = df["Screen Size"].apply(extract_number)

# Prices cleanup (extract numbers, keep max if multiple)
for col in ["Launched Price (Pakistan)", "Launched Price (India)", 
            "Launched Price (China)", "Launched Price (USA)", "Launched Price (Dubai)"]:
    df[col] = df[col].apply(extract_number)

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Company Name               930 non-null    object
 1   Model Name                 930 non-null    object
 2   Mobile Weight              930 non-null    float64
 3   RAM                        930 non-null    float64
 4   Front Camera               930 non-null    float64
 5   Back Camera                930 non-null    float64
 6   Processor                  930 non-null    object
 7   Battery Capacity           930 non-null    float64
 8   Screen Size                930 non-null    float64
 9   Launched Price (Pakistan)  929 non-null    float64
 10  Launched Price (India)     930 non-null    float64
 11  Launched Price (China)     930 non-null    float64
 12  Launched Price (USA)       930 non-null    float64
 13  Launched Price (Dubai)     930 non-null    float64
 14  Launched Year              930 non-null    int64
dtypes: float64(11), int64(1), object(3)
memory usage: 109.1+ KB

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
0,Apple,iPhone 16 128GB,174.0,6.0,12.0,48.0,A17 Bionic,600.0,6.1,999.0,999.0,799.0,799.0,799.0,2024
1,Apple,iPhone 16 256GB,174.0,6.0,12.0,48.0,A17 Bionic,600.0,6.1,999.0,999.0,99.0,849.0,999.0,2024
2,Apple,iPhone 16 512GB,174.0,6.0,12.0,48.0,A17 Bionic,600.0,6.1,999.0,999.0,499.0,899.0,199.0,2024
3,Apple,iPhone 16 Plus 128GB,203.0,6.0,12.0,48.0,A17 Bionic,200.0,6.7,999.0,999.0,199.0,899.0,199.0,2024
4,Apple,iPhone 16 Plus 256GB,203.0,6.0,12.0,48.0,A17 Bionic,200.0,6.7,999.0,999.0,499.0,949.0,399.0,2024

### Cleaning Units & Converting to Numeric

In [28]:
cleaned_file = "/mnt/data/Mobiles_Dataset_Cleaned.csv"
mobiles_df.to_csv(cleaned_file, index=False)
print("Cleaned dataset saved at:", cleaned_file)

NameError: name 'mobiles_df' is not defined

In [32]:
import pandas as pd

# Load raw dataset
file_path = "/mnt/data/Mobiles Dataset (2025).csv"
mobiles_df = pd.read_csv(file_path)

# Cleaning
mobiles_df = mobiles_df.drop_duplicates()
mobiles_df = mobiles_df.dropna(how="all")
mobiles_df.columns = mobiles_df.columns.str.strip().str.replace(" ", "_")

# Save cleaned dataset
cleaned_file = "/mnt/data/Mobiles_Dataset_Cleaned.csv"
mobiles_df.to_csv(cleaned_file, index=False)

print("✅ Cleaned dataset saved at:", cleaned_file)

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data/Mobiles Dataset (2025).csv'

In [26]:
# 📌 Step 2: Data Cleaning (safe version)

# Convert everything to string first before cleaning
df["Mobile Weight"] = (
    df["Mobile Weight"].astype(str).str.replace("g", "", regex=False).replace("nan", np.nan).astype(float)
)

df["RAM"] = (
    df["RAM"].astype(str).str.replace("GB", "", regex=False).replace("nan", np.nan).astype(float)
)

df["Front Camera"] = (
    df["Front Camera"].astype(str).str.replace("MP", "", regex=False).replace("nan", np.nan).astype(float)
)

df["Back Camera"] = (
    df["Back Camera"].astype(str).str.replace("MP", "", regex=False).replace("nan", np.nan).astype(float)
)

df["Battery Capacity"] = (
    df["Battery Capacity"].astype(str)
    .str.replace("mAh", "", regex=False)
    .str.replace(",", "", regex=False)
    .replace("nan", np.nan)
    .astype(float)
)

df["Screen Size"] = (
    df["Screen Size"].astype(str).str.replace("inches", "", regex=False).replace("nan", np.nan).astype(float)
)

# Prices cleanup
for col in ["Launched Price (Pakistan)", "Launched Price (India)", 
            "Launched Price (China)", "Launched Price (USA)", "Launched Price (Dubai)"]:
    df[col] = (
        df[col].astype(str)
        .str.replace(r"[^\d.]", "", regex=True)   # keep only digits & decimals
        .replace("", np.nan)
        .astype(float)
    )

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Company Name               930 non-null    object
 1   Model Name                 930 non-null    object
 2   Mobile Weight              930 non-null    float64
 3   RAM                        930 non-null    float64
 4   Front Camera               930 non-null    float64
 5   Back Camera                930 non-null    float64
 6   Processor                  930 non-null    object
 7   Battery Capacity           930 non-null    float64
 8   Screen Size                930 non-null    float64
 9   Launched Price (Pakistan)  929 non-null    float64
 10  Launched Price (India)     930 non-null    float64
 11  Launched Price (China)     930 non-null    float64
 12  Launched Price (USA)       930 non-null    float64
 13  Launched Price (Dubai)     930 non-null    float64
 14  Launched Year              930 non-null    int64
dtypes: float64(11), int64(1), object(3)
memory usage: 109.1+ KB

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
0,Apple,iPhone 16 128GB,174.0,6.0,12.0,48.0,A17 Bionic,600.0,6.1,999.0,999.0,799.0,799.0,799.0,2024
1,Apple,iPhone 16 256GB,174.0,6.0,12.0,48.0,A17 Bionic,600.0,6.1,999.0,999.0,99.0,849.0,999.0,2024
2,Apple,iPhone 16 512GB,174.0,6.0,12.0,48.0,A17 Bionic,600.0,6.1,999.0,999.0,499.0,899.0,199.0,2024
3,Apple,iPhone 16 Plus 128GB,203.0,6.0,12.0,48.0,A17 Bionic,200.0,6.7,999.0,999.0,199.0,899.0,199.0,2024
4,Apple,iPhone 16 Plus 256GB,203.0,6.0,12.0,48.0,A17 Bionic,200.0,6.7,999.0,999.0,499.0,949.0,399.0,2024